{{ 
    config (alias= 'APORA_INDUSTRY_SALES_FRCST' , materialized = 'table', schema = 'MARKETING_INSIGHT' )
}}

WITH CTE AS (
SELECT * FROM 
    APITDBPRD.EXT_INDUSTRY_DAT.APORA_INDUSTRY_SALES_FRCST
)

SELECT * FROM CTE