{{ 
    config (materialized = 'view', schema = 'MARKETING_INSIGHT' )
}}


WITH CTE AS
(
    SELECT COUNTRY,
           REGION,
            TIRESIZE,
            RIMSIZE,
            CONCAT(RIMSIZE,'"') AS RIM,
            CASE WHEN RIMSIZE >=18 THEN '18+'
                 ELSE '17-' END AS RIMGROUP,
            VERSION,
            CARSEGMENT,
            REPLMARKET,
            GYVOLUME,
            CASE WHEN YEAR(MEASUREYEAR)<2021 THEN 0
                 ELSE CPVOLUME END AS CPVOLUME,
            MEASUREYEAR
    FROM APITDBPRD.MARKETING_INSIGHT.REPL_VOLUME
    WHERE MEASUREYEAR <= (
        SELECT MAX(A.MONTHDATE)
        FROM APITDBPRD.MARKETING_INSIGHT.APORA_SALES_ACTUALS_FORECAST A
        LEFT JOIN APITDBPRD.STAGING.EDW_MASTER_PRODUCT B
        ON A.MATERIALID = B.MATERIALID
        WHERE B.BRANDNAME = 'Goodyear')
    AND MEASUREYEAR >= (
        SELECT MIN(MEASURE_YEAR)
        FROM APITDBPRD.STAGING.APORA_INDUSTRY_SALES_FRCST
    )  
)

SELECT * FROM CTE